### ISSUE TITLE
Deprecation Log

### ISSUE THREAD

**Issue by vimal-360** [hendurhance/laravel-spam-email#5]
Hello, We are using version 2.0 in our project. It shows 2.0 in composer.json as well. but we keep getting the following log. Tried uninstalling, cache remove, vendor, remove, and event composer.lock remove. still, we are getting this log.

```log
Since martian/spammailchecker 1.0.0: This package is deprecated and will no longer be maintained. Please use version 2.0.0 or higher. in /home/{full_path}/vendor/symfony/deprecation-contracts/function.php on line 25
```

**Comment by vimal-360** [comment]
I think it requires a conditional log

```php
<?php

namespace Martian\SpamMailChecker\Providers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\ServiceProvider;
use Martian\SpamMailChecker\SpamMailChecker;
use Martian\SpamMailChecker\Builders\ConfigBuilder;
class SpamMailCheckerServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     */
    public function boot()
    {
        // Depreciation Notice
        trigger_deprecation('martian/spammailchecker', '1.0.0', 'This package is deprecated and will no longer be maintained. Please use version 2.0.0 or higher.');

        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../../config/laravel-spammail-checker.php' => config_path('laravel-spammail-checker.php'),
            ], 'config');
        }

        // Extend Validator
        $this->extendValidator();
    }
```

**Comment by hendurhance** [comment]
To resolve this issue, update the package version constraint in your composer.json file to explicitly require version 2.0 or higher.

You can do this in your composer.json and update it to specify the version constraint like this:

``` json
"require": {
    "martian/spammailchecker": "^2.0"
}
```
After updating the version constraint, run composer update martian/spammailchecker to fetch the latest version that satisfies the constraint. This should resolve the deprecation notice.

**Comment by vimal-360** [comment]
![Screenshot 2024-03-06 at 3 32 07 PM](https://github.com/hendurhance/laravel-spam-email/assets/95009456/d9d0429d-8538-4bb6-912b-dbd102653ed2)
See my composer.json . I already mentioned ` We are using version 2.0`

**Comment by hendurhance** [comment]
Try the new release v2.0.1.
